# Generated by Django 6.0.6 on 2026-07-02 06:53

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_first_name_remove_employee_hire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, default=employees.models.generate_employee_id, max_length=12, null=True),
        ),
    ]
