# Generated by Django 6.0.6 on 2026-07-02 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_employee_ids(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    used_ids = set(
        Employee.objects.exclude(employee_id__isnull=True).values_list('employee_id', flat=True)
    )
    next_id = max(used_ids) + 1 if used_ids else 1000
    for emp in Employee.objects.filter(employee_id__isnull=True):
        while next_id in used_ids:
            next_id += 1
        emp.employee_id = next_id
        emp.save()
        used_ids.add(next_id)
        next_id += 1


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_employee_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(populate_employee_ids),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(unique=True),
        ),
    ]
